editor:
  productDescription: null
  categoryShortDescription: null
  categoryDescription: null

limitItems: 12
allowedPerPage:
  - 12
  - 24
  - 36
sort: name.asc
minSearchChars: 3
showSubcategoryProducts: true
delimiterOptions: "|"
mailer:
  from: [email, name]
  address: []
formSendRequest:
  useCaptcha: true
  captchaClass: Enjoys\Forms\Captcha\reCaptcha\reCaptcha

thumbnailCreationService: \EnjoysCMS\Module\Catalog\Crud\Images\ThumbnailService\DefaultThumbnailCreationService

storageUploads:
  image_default:
    EnjoysCMS\Core\StorageUpload\Local:
      rootDirectory: /public/upload/catalog
      publicUrl: /upload/catalog
      permissionMap:
        dir:
          private: 0o755

  file_default:
    EnjoysCMS\Core\StorageUpload\Local:
      rootDirectory: /public/upload/catalog_files
      publicUrl: /upload/catalog_files
      permissionMap:
        dir:
          private: 0o755

productImageStorage: image_default
productFileStorage: file_default
allocatedMemoryDynamically: true

categoryMetaTitleCallback: ~
categoryMetaDescriptionCallback: ~
categoryMetaKeywordsCallback: ~

productMetaTitleCallback: ~
productMetaDescriptionCallback: ~
productMetaKeywordsCallback: ~

indexMetaTitleCallback: ~
indexMetaDescriptionCallback: ~
indexMetaKeywordsCallback: ~

currency:
  default: RUB
  ratio:
#    USDRUB: 1.15

admin:
  searchFields:
    - p.name
    - p.productCode
