WYSIWYG: summernote
limitItems: 12
showSubcategoryProducts: true
mailer:
  from: [email, name]
  address: []
formSendRequest:
  useCaptcha: true
  captchaClass: Enjoys\Forms\Captcha\reCaptcha\reCaptcha
