WYSIWYG: summernote
limitItems: 12
minSearchChars: 3
showSubcategoryProducts: true
delimiterOptions: "|"
mailer:
  from: [email, name]
  address: []
formSendRequest:
  useCaptcha: true
  captchaClass: Enjoys\Forms\Captcha\reCaptcha\reCaptcha
manageUploads:
  image:
    EnjoysCMS\Module\Catalog\LocalUpload:
      rootDirectory: /public/upload/catalog

  files:
    EnjoysCMS\Module\Catalog\LocalUpload:
      rootDirectory: /upload/files
