WYSIWYG: summernote
limitItems: 12
minSearchChars: 3
showSubcategoryProducts: true
delimiterOptions: "|"
mailer:
  from: [email, name]
  address: []
formSendRequest:
  useCaptcha: true
  captchaClass: Enjoys\Forms\Captcha\reCaptcha\reCaptcha
manageUploads:
  thumbnail:
    EnjoysCMS\Module\Catalog\Crud\Images\ThumbnailService\DefaultThumbnailService:
  image:
    EnjoysCMS\Module\Catalog\StorageUpload\Local:
      rootDirectory: /public/upload/catalog/xx
      permissionMap:
        dir:
          private: 0755
