WYSIWYG: summernote
limitItems: 12
allowedPerPage:
  - 12
  - 24
  - 36
sort: name.asc
minSearchChars: 3
showSubcategoryProducts: true
delimiterOptions: "|"
mailer:
  from: [email, name]
  address: []
formSendRequest:
  useCaptcha: true
  captchaClass: Enjoys\Forms\Captcha\reCaptcha\reCaptcha

thumbnailService:
  EnjoysCMS\Module\Catalog\Crud\Images\ThumbnailService\DefaultThumbnailService: []

storageUploads:
  image_default:
    EnjoysCMS\Core\StorageUpload\Local:
      rootDirectory: /public/upload/catalog
      publicUrl: /upload/catalog
      permissionMap:
        dir:
          private: 0755

  file_default:
    EnjoysCMS\Core\StorageUpload\Local:
      rootDirectory: /public/upload/catalog_files
      publicUrl: /upload/catalog_files
      permissionMap:
        dir:
          private: 0755

productImageStorage: image_default
productFileStorage: file_default
allocatedMemoryDynamically: true

currency:
  default: RUB
  ratio:
#    USDRUB: 1.15
