WYSIWYG: summernote
limitItems: 12
minSearchChars: 3
showSubcategoryProducts: true
delimiterOptions: "|"
mailer:
  from: [email, name]
  address: []
formSendRequest:
  useCaptcha: true
  captchaClass: Enjoys\Forms\Captcha\reCaptcha\reCaptcha
